import React from 'react'

const Historia = () => {


    return (
        <div>
            <h1> Historia Cmentarza </h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo repellendus praesentium eum fuga consectetur, asperiores cupiditate aliquam voluptatem veritatis nam magni harum debitis similique facilis dolores eligendi impedit? Dignissimos iusto quasi architecto officia sequi laboriosam accusantium in sed? Aliquid praesentium velit eveniet reprehenderit facere nemo, quis tenetur soluta vero fuga libero sapiente ipsum fugit ipsa deserunt beatae laborum eaque id repudiandae iure? Accusamus, dolorem commodi. Tenetur, tempora maiores expedita enim est facilis ut quod consequuntur. Consectetur, ullam. Deleniti doloribus beatae ipsa ab animi inventore incidunt excepturi earum non exercitationem? Expedita explicabo pariatur amet totam optio aspernatur labore laborum tempore maxime?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo repellendus praesentium eum fuga consectetur, asperiores cupiditate aliquam voluptatem veritatis nam magni harum debitis similique facilis dolores eligendi impedit? Dignissimos iusto quasi architecto officia sequi laboriosam accusantium in sed? Aliquid praesentium velit eveniet reprehenderit facere nemo, quis tenetur soluta vero fuga libero sapiente ipsum fugit ipsa deserunt beatae laborum eaque id repudiandae iure? Accusamus, dolorem commodi. Tenetur, tempora maiores expedita enim est facilis ut quod consequuntur. Consectetur, ullam. Deleniti doloribus beatae ipsa ab animi inventore incidunt excepturi earum non exercitationem? Expedita explicabo pariatur amet totam optio aspernatur labore laborum tempore maxime? Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo repellendus praesentium eum fuga consectetur, asperiores cupiditate aliquam voluptatem veritatis nam magni harum debitis similique facilis dolores eligendi impedit? Dignissimos iusto quasi architecto officia sequi laboriosam accusantium in sed? Aliquid praesentium velit eveniet reprehenderit facere nemo, quis tenetur soluta vero fuga libero sapiente ipsum fugit ipsa deserunt beatae laborum eaque id repudiandae iure? Accusamus, dolorem commodi. Tenetur, tempora maiores expedita enim est facilis ut quod consequuntur. Consectetur, ullam. Deleniti doloribus beatae ipsa ab animi inventore incidunt excepturi earum non exercitationem? Expedita explicabo pariatur amet totam optio aspernatur labore laborum tempore maxime?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo repellendus praesentium eum fuga consectetur, asperiores cupiditate aliquam voluptatem veritatis nam magni harum debitis similique facilis dolores eligendi impedit? Dignissimos iusto quasi architecto officia sequi laboriosam accusantium in sed? Aliquid praesentium velit eveniet reprehenderit facere nemo, quis tenetur soluta vero fuga libero sapiente ipsum fugit ipsa deserunt beatae laborum eaque id repudiandae iure? Accusamus, dolorem commodi. Tenetur, tempora maiores expedita enim est facilis ut quod consequuntur. Consectetur, ullam. Deleniti doloribus beatae ipsa ab animi inventore incidunt excepturi earum non exercitationem? Expedita explicabo pariatur amet totam optio aspernatur labore laborum tempore maxime? Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo repellendus praesentium eum fuga consectetur, asperiores cupiditate aliquam voluptatem veritatis nam magni harum debitis similique facilis dolores eligendi impedit? Dignissimos iusto quasi architecto officia sequi laboriosam accusantium in sed? Aliquid praesentium velit eveniet reprehenderit facere nemo, quis tenetur soluta vero fuga libero sapiente ipsum fugit ipsa deserunt beatae laborum eaque id repudiandae iure? Accusamus, dolorem commodi. Tenetur, tempora maiores expedita enim est facilis ut quod consequuntur. Consectetur, ullam. Deleniti doloribus beatae ipsa ab animi inventore incidunt excepturi earum non exercitationem? Expedita explicabo pariatur amet totam optio aspernatur labore laborum tempore maxime?</p>
        
        </div>
    )
}

export default Historia
